### PR TITLE
First iteration on brainomics2 schema

### PR DESCRIPTION
**Pull request by dgoyard**

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
Careful with copyrights. The copyright is shared with Logilab. Please change the headers.
Also I would recommend not referring to NSAp in the headers because lots of people have contributed to this code.

**Comment by DimitriPapadopoulos** [comment]
Do we need to fork cubicweb-file?

I would rather use Logilab's version if at all possible because this looks like a generic need better handled by Logilab and far from our core domain.

**Comment by dgoyard** [comment]
copyrights updated.

As mentioned, this is a FIRST (alpha) version from which the brainomics2 schema will be built. We don't know if's we'll use the "File" entity. if not, we may not even use the File cube.

**Comment by DimitriPapadopoulos** [comment]
I guess my question about File is, have we actually modified Logilab's cubicweb-file? If not, it does not have to be added here. If it has been modified, it should indeed be here - and possibly further discussed later on.

**Comment by AGrigis** [comment]
I will check if the File entity has been modified and make the modification in another PR if necessary.

**Comment by dgoyard** [comment]
So far the File entity has NOT been modified.
We are not using it so far (only "ExternalFiles" and "Fileset" entities). I don't know if we'll use it in the new business logic cube.
I suggest that either we modify it in order to use it or we get rid of the whole cube.

**Pull request merged**
